language: python
cache: pip
python:
  - 3.8
install:
  - pip install "Nikola[extras]"
script:
  - nikola build
deploy:
  provider: pages
  target-branch: master
  local-dir: output
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: src
