name: Renovate
on:
  workflow_dispatch:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0 7 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: pieterdavid.github.io
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Self-hosted renovate
        uses: renovatebot/github-action@v40.3.4
        with:
          configurationFile: .github/renovate/config.json5
          token: '${{ steps.app-token.outputs.token }}'
        env:
          RENOVATE_PLATFORM_COMMIT: 'true'
